In [1]:
import pandas as pd
import numpy as np

In [2]:
# 데이터 불러오기. y값은 이미 범주형으로 되어있음.
dat_wine=pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/'
                     'wine/wine.data',header=None)
dat_wine.head()
dat_wine.columns = ['class label', 'alchohol', 'malic acid', 'ash', 
                    'alcalinity of ash', 'magnesium', 'total phenols', 
                    'flavanoids', 'nonflavanoid phenols', 
                    'proanthocyanins', 'color intensity', 'hue', 
                    'OD208', 'proline']  # Column names
print('class label:', np.unique(dat_wine['class label']))  # Class 출력
dat_wine.head()

class label: [1 2 3]


class label  alchohol  malic acid  ...   hue  OD208  proline
0            1     14.23        1.71  ...  1.04   3.92     1065
1            1     13.20        1.78  ...  1.05   3.40     1050
2            1     13.16        2.36  ...  1.03   3.17     1185
3            1     14.37        1.95  ...  0.86   3.45     1480
4            1     13.24        2.59  ...  1.04   2.93      735

[5 rows x 14 columns]

In [19]:
# 전체 data를 training set과 test set으로 split
from sklearn.model_selection import train_test_split
X, y = dat_wine.iloc[:,1:].values, dat_wine.iloc[:,0].values
X_train, X_test, y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=1, stratify=y)

In [4]:
# 표준화
from sklearn.preprocessing import StandardScaler
std = StandardScaler()
X_train_std = std.fit_transform(X_train)
X_test_std = std.transform(X_test)

In [17]:
# Logistic Regression with L2 or L1 Regularization
from sklearn.linear_model import LogisticRegression
lr2_10 = LogisticRegression(penalty='l2', C=10.0, solver='saga')  # L2 with C(=1/λ)=10
lr2_1 = LogisticRegression(penalty='l2', C=1.0, solver='saga')    # L2 with C(=1/λ)=1
lr2_0_1 = LogisticRegression(penalty='l2', C=0.1, solver='saga')  # L2 with C(=1/λ)=0.1

lr1_10 = LogisticRegression(penalty='l1', C=10.0, solver='saga')  # L1 with C(=1/λ)=10
lr1_1 = LogisticRegression(penalty='l1', C=1.0, solver='saga')    # L1 with C(=1/λ)=1
lr1_0_1 = LogisticRegression(penalty='l1', C=0.1, solver='saga')  # L1 with C(=1/λ)=0.1

In [18]:
# 규제화 방법(L2 or L1)과 규제강도(λ)를 바꿔가며 accuracy score 계산
lr2_10.fit(X_train_std, y_train)
print('Training accuracy with L2 and λ=0.1:', lr2_10.score(X_train_std, y_train))
print('Test accuracy with L2 and λ=0.1:', lr2_10.score(X_test_std, y_test))

lr2_1.fit(X_train_std, y_train)  # warning..
print('Training accuracy with L2 and λ=1:', lr2_1.score(X_train_std, y_train))
print('Test accuracy with L2 and λ=1:', lr2_1.score(X_test_std, y_test))

lr2_0_1.fit(X_train_std, y_train)
print('Training accuracy with L2 and λ=10:', lr2_0_1.score(X_train_std, y_train))
print('Test accuracy with L2 and λ=10:', lr2_0_1.score(X_test_std, y_test))

lr1_10.fit(X_train_std, y_train)
print('Training accuracy with L1 and λ=0.1:', lr1_10.score(X_train_std, y_train))
print('Test accuracy with L1 and λ=0.1:', lr1_10.score(X_test_std, y_test))

lr1_1.fit(X_train_std, y_train)
print('Training accuracy with L1 and λ=1:', lr1_1.score(X_train_std, y_train))
print('Test accuracy with L1 and λ=1:', lr1_1.score(X_test_std, y_test))

lr1_0_1.fit(X_train_std, y_train)
print('Training accuracy with L1 and λ=10:', lr1_0_1.score(X_train_std, y_train))
print('Test accuracy with L1 and λ=10:', lr1_0_1.score(X_test_std, y_test))

Training accuracy with L2 and λ=0.1: 1.0
Test accuracy with L2 and λ=0.1: 0.9814814814814815
Training accuracy with L2 and λ=1: 1.0
Test accuracy with L2 and λ=1: 0.9814814814814815
Training accuracy with L2 and λ=10: 1.0
Test accuracy with L2 and λ=10: 1.0
Training accuracy with L1 and λ=0.1: 1.0
Test accuracy with L1 and λ=0.1: 0.9814814814814815
Training accuracy with L1 and λ=1: 1.0
Test accuracy with L1 and λ=1: 0.9814814814814815
Training accuracy with L1 and λ=10: 0.967741935483871
Test accuracy with L1 and λ=10: 0.9444444444444444


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


In [13]:
# L2 규제의 규제강도(C=1/λ)를 바꿔가며 계수 추정치 관찰
print(lr2_10.intercept_)
print(lr2_1.intercept_)
print(lr2_0_1.intercept_)

print(lr2_10.coef_)
print(lr2_1.coef_)
print(lr2_0_1.coef_)

[ 0.32296362  0.60033615 -0.92329977]
[ 0.28173282  0.6024029  -0.88413572]
[ 0.0683881   0.45688086 -0.52526895]
[[ 1.25664178  0.15899529  0.39926374 -1.53634982  0.08473759  0.37407767
   0.83876311 -0.28751864  0.09268499  0.12775152  0.0722625   0.97188895
   1.39116593]
 [-1.5372395  -0.43915291 -1.23984712  1.21218732 -0.32703465 -0.51670074
   0.85895303  0.40866438  0.39442514 -1.36535608  1.14060554  0.02219384
  -1.75612335]
 [ 0.28059772  0.28015763  0.84058338  0.32416249  0.24229707  0.14262307
  -1.69771614 -0.12114574 -0.48711013  1.23760457 -1.21286804 -0.99408279
   0.36495742]]
[[ 0.75495729  0.06165881  0.2336697  -0.8925231   0.02649841  0.29464787
   0.56064124 -0.2071806   0.13401678  0.12719203  0.10165733  0.61737663
   0.90976587]
 [-0.98657135 -0.32327905 -0.65176965  0.66792906 -0.22933211 -0.20753188
   0.43824097  0.19874428  0.24373934 -0.78043161  0.63697798  0.08558965
  -1.03461549]
 [ 0.23161406  0.26162025  0.41809995  0.22459404  0.2028337  -0.08711

In [14]:
# L1 규제의 규제강도(C=1/λ)를 바꿔가며 계수 추정치 관찰
print(lr1_10.intercept_)
print(lr1_1.intercept_)
print(lr1_0_1.intercept_)

print(lr1_10.coef_)
print(lr1_1.coef_)
print(lr1_0_1.coef_)

[ 0.39334184  0.5958625  -0.98920434]
[ 0.28462985  0.54413385 -0.8287637 ]
[ 0.05085504  0.30693808 -0.35779311]
[[ 1.19997383e+00  0.00000000e+00  1.54580407e-01 -1.57710818e+00
   0.00000000e+00  2.84110640e-01  8.25653391e-01  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  8.79401443e-01
   1.62309433e+00]
 [-1.78064452e+00 -4.56713816e-01 -1.47383462e+00  1.05802427e+00
  -2.92893382e-01 -4.06457188e-01  7.01037258e-01  4.65557053e-01
   2.08045179e-01 -1.56217122e+00  1.10248967e+00  0.00000000e+00
  -1.93798201e+00]
 [ 5.39392997e-02  1.17354860e-01  7.93799029e-01  0.00000000e+00
   1.77579266e-01  0.00000000e+00 -2.03734189e+00 -6.11569248e-06
  -3.41178760e-01  1.12646922e+00 -1.21297461e+00 -9.54584609e-01
   0.00000000e+00]]
[[ 0.0313239   0.          0.         -1.17721748  0.          0.
   0.02148411  0.          0.          0.          0.          0.62105
   0.97646011]
 [-1.58450657 -0.1446383  -0.77389205  0.04388529 -0.0731721   0.
   0.          0

In [ ]:
lr2_10.fit(X_train, y_train)
print('Training accuracy with L2 and λ=0.1:', lr2_10.score(X_train, y_train))
print('Test accuracy with L2 and λ=0.1:', lr2_10.score(X_test, y_test))

lr2_1.fit(X_train, y_train)  # warning..
print('Training accuracy with L2 and λ=1:', lr2_1.score(X_train, y_train))
print('Test accuracy with L2 and λ=1:', lr2_1.score(X_test, y_test))

lr2_0_1.fit(X_train, y_train)
print('Training accuracy with L2 and λ=10:', lr2_0_1.score(X_train, y_train))
print('Test accuracy with L2 and λ=10:', lr2_0_1.score(X_test, y_test))

lr1_10.fit(X_train, y_train)
print('Training accuracy with L1 and λ=0.1:', lr1_10.score(X_train, y_train))
print('Test accuracy with L1 and λ=0.1:', lr1_10.score(X_test, y_test))

lr1_1.fit(X_train, y_train)
print('Training accuracy with L1 and λ=1:', lr1_1.score(X_train, y_train))
print('Test accuracy with L1 and λ=1:', lr1_1.score(X_test, y_test))

lr1_0_1.fit(X_train, y_train)
print('Training accuracy with L1 and λ=10:', lr1_0_1.score(X_train, y_train))
print('Test accuracy with L1 and λ=10:', lr1_0_1.score(X_test, y_test))

Training accuracy with L2 and λ=0.1: 1.0
Test accuracy with L2 and λ=0.1: 0.9444444444444444
Training accuracy with L2 and λ=1: 0.9838709677419355
Test accuracy with L2 and λ=1: 0.9444444444444444
Training accuracy with L2 and λ=10: 0.9758064516129032
Test accuracy with L2 and λ=10: 0.9259259259259259
Training accuracy with L1 and λ=0.1: 1.0
Test accuracy with L1 and λ=0.1: 0.9074074074074074
Training accuracy with L1 and λ=1: 0.9838709677419355
Test accuracy with L1 and λ=1: 0.9074074074074074
Training accuracy with L1 and λ=10: 0.9354838709677419
Test accuracy with L1 and λ=10: 0.8888888888888888


C:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to

In [ ]:
print(lr2_10.intercept_)
print(lr2_1.intercept_)
print(lr2_0_1.intercept_)

print(lr2_10.coef_)
print(lr2_1.coef_)
print(lr2_0_1.coef_)

[-0.96456004  1.34118396 -0.22390307]
[-0.16655119  0.26945958 -0.07022366]
[-0.02988443  0.05684191 -0.02613036]
[[-8.35654939e-01  1.44150350e+00  1.46570959e+00 -1.27574191e+00
   2.09578947e-02  9.54417242e-01  3.00222626e+00 -7.24568499e-02
  -1.22897003e+00 -5.54461321e-01 -1.84306873e-02  6.28614504e-01
   2.67981633e-02]
 [ 1.09359574e+00 -2.12095717e+00 -1.21322442e+00  7.34605497e-01
  -1.75690138e-02 -1.04233634e+00  1.23716271e+00  2.85603369e+00
   1.60402367e+00 -2.48226700e+00  3.26535993e+00 -6.66781906e-01
  -2.21810800e-02]
 [-7.02348476e-01  1.19098753e+00  5.88127902e-01  4.03900064e-02
   7.27945504e-02 -3.70618302e-01 -3.76294649e+00 -6.02758148e-01
  -7.46352348e-01  1.33638830e+00 -1.36735959e+00 -2.11442785e+00
   2.97823296e-03]]
[[-3.58983950e-01  4.10637468e-01  3.53872093e-01 -7.42979348e-01
  -3.36933385e-02  5.44683231e-01  1.12999767e+00 -5.75279878e-02
   5.03329511e-02 -1.89873020e-01  7.55818484e-03  6.14639419e-01
   2.00108374e-02]
 [ 5.83708283e-01

In [ ]:
print(lr1_10.intercept_)
print(lr1_1.intercept_)
print(lr1_0_1.intercept_)

print(lr1_10.coef_)
print(lr1_1.coef_)
print(lr1_0_1.coef_)

[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[[-1.01302850e+00  2.39608807e+00  1.71991521e-01 -1.86127869e+00
   8.34950377e-02  0.00000000e+00  7.14119679e+00  0.00000000e+00
  -2.97774639e+00 -8.18214103e-01  0.00000000e+00  0.00000000e+00
   3.49411930e-02]
 [ 1.31679390e+00 -2.73038551e+00 -3.38001837e+00  9.41289186e-01
   0.00000000e+00 -1.95012089e+00  1.91790955e+00  1.23238533e+01
   2.58858839e+00 -3.24670367e+00  4.31646082e+00 -5.15270908e-01
  -2.73681581e-02]
 [-2.78642772e-01  1.40323545e+00  0.00000000e+00  3.31841490e-02
   1.17547347e-01  0.00000000e+00 -7.98095839e+00  0.00000000e+00
   0.00000000e+00  1.24944131e+00 -2.20232349e+00 -3.76082391e+00
  -6.33896232e-04]]
[[-2.34793075e-02  8.11723037e-02  0.00000000e+00 -7.05407269e-01
  -4.59876204e-02  0.00000000e+00  1.97035783e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.76174386e-02]
 [ 5.87514555e-01 -1.21890126e+00  0.00000000e+00  4.28854104e-01
   2.44013384e-02  0.00000000e+0